import Head from "next/head";
import Image from "next/image";
import { Content, Inter } from "next/font/google";
import { useState, useEffect } from "react";
import styles from "./page.module.css";
import { Clock } from "@/components/Clock";
import { CenterNav } from "@/components/UI/CenterNav";
import { TopNav } from "@/components/UI/TopNav";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [activePage, setActivePage] = useState("About");

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <TopNav />
        <div className={styles.wrapper}>
          <div className={styles.topBar}>
            <span className={styles.activePage}>{activePage}</span>
          </div>

          <CenterNav />

          <div className={styles.bottomContainer}>
            <Clock />
            <div>Other</div>
          </div>
        </div>
      </main>
    </>
  );
}
